--Privileges/Permissions for the IBM DB2 for i  

--DB2 for i catalog views (QSYS2)
SELECT * FROM QSYS2.SYSCOLAUTH;
SELECT * FROM QSYS2.SYSPACKAGEAUTH;
SELECT * FROM QSYS2.SYSROUTINEAUTH;
SELECT * FROM QSYS2.SYSSCHEMAAUTH;
SELECT * FROM QSYS2.SYSSEQUENCEAUTH;
SELECT * FROM QSYS2.SYSTABAUTH;
SELECT * FROM QSYS2.SYSUDTAUTH;
SELECT * FROM QSYS2.SYSVARIABLEAUTH;
SELECT * FROM QSYS2.SYSXSROBJECTAUTH;

--ODBC and JDBCTM catalog views (SYSIBM)
SELECT * FROM SQLCOLPRIVILEGES;
SELECT * FROM SQLTABLEPRIVILEGES;

--ANS and ISO catalog views (QSYS2)
SELECT * FROM QSYS2.AUTHORIZATIONS;
SELECT * FROM QSYS2.ROUTINE_PRIVILEGES;
SELECT * FROM QSYS2.UDT_PRIVILEGES;
SELECT * FROM QSYS2.USAGE_PRIVILEGES;
SELECT * FROM QSYS2.VARIABLE_PRIVILEGES;
